# Compliance configuration generated by CloudGeni
# Control: S3.9
# Resource: arn:aws:s3:::astro-astronuts-org-avatars

provider "aws" {
  region = "us-east-1"
}

terraform {
  required_version = ">= 1.0.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
